version: "1.0.0"
services:
  postgres:
    image: postgres:latest
    networks:
      - postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /var/lib/pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env

  nestjs-api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: nestjs-api
    env_file:
      - docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

  app:
    container_name: app_app
    image: autos_app
    ports:
      - 5173:5173
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - docker.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
