export const details = [
  { fullname: 'Oil Change', serviceable: true, price: 50 },
  { fullname: 'Tire Rotation', serviceable: true, price: 30 },
  { fullname: 'Brake Replacement', serviceable: false, price: 200 },
  { fullname: 'Engine Tune-Up', serviceable: true, price: 150 },
  { fullname: 'Transmission Flush', serviceable: false, price: 300 },
  { fullname: 'Battery Replacement', serviceable: true, price: 120 },
  { fullname: 'Wheel Alignment', serviceable: true, price: 80 },
  { fullname: 'Air Filter Replacement', serviceable: false, price: 40 },
  { fullname: 'Coolant Flush', serviceable: true, price: 100 },
  { fullname: 'Spark Plug Replacement', serviceable: true, price: 80 },
  { fullname: 'Brake Pad Replacement', serviceable: false, price: 250 },
  { fullname: 'Headlight Bulb Replacement', serviceable: true, price: 20 },
  { fullname: 'Power Steering Fluid Change', serviceable: false, price: 120 },
  { fullname: 'Cabin Air Filter Replacement', serviceable: true, price: 50 },
  { fullname: 'Wiper Blade Replacement', serviceable: true, price: 25 },
  { fullname: 'Fuel Filter Replacement', serviceable: false, price: 90 },
  { fullname: 'Radiator Flush', serviceable: true, price: 120 },
  { fullname: 'Brake Caliper Replacement', serviceable: false, price: 350 },
  { fullname: 'Alternator Replacement', serviceable: true, price: 300 },
  { fullname: 'Steering Rack Replacement', serviceable: false, price: 400 },
  { fullname: 'AC Recharge', serviceable: true, price: 80 },
  { fullname: 'Exhaust System Inspection', serviceable: true, price: 60 },
  { fullname: 'Oxygen Sensor Replacement', serviceable: false, price: 150 },
  { fullname: 'Timing Belt Replacement', serviceable: true, price: 400 },
  { fullname: 'Ignition Coil Replacement', serviceable: true, price: 100 },
  { fullname: 'Thermostat Replacement', serviceable: false, price: 80 },
  { fullname: 'Drive Belt Replacement', serviceable: true, price: 70 },
  { fullname: 'Wheel Bearing Replacement', serviceable: false, price: 200 },
  { fullname: 'PCV Valve Replacement', serviceable: true, price: 40 },
  { fullname: 'EGR Valve Cleaning', serviceable: true, price: 80 },
  { fullname: 'Suspension Inspection', serviceable: false, price: 150 },
  { fullname: 'Starter Motor Replacement', serviceable: true, price: 200 },
  {
    fullname: 'Intake Manifold Gasket Replacement',
    serviceable: true,
    price: 120,
  },
  {
    fullname: 'Catalytic Converter Replacement',
    serviceable: false,
    price: 1000,
  },
  { fullname: 'Brake Fluid Change', serviceable: true, price: 70 },
  { fullname: 'Fuel Injector Cleaning', serviceable: true, price: 120 },
  { fullname: 'Clutch Replacement', serviceable: false, price: 500 },
  { fullname: 'Tie Rod End Replacement', serviceable: true, price: 90 },
  {
    fullname: 'Camshaft Position Sensor Replacement',
    serviceable: false,
    price: 80,
  },
  { fullname: 'Door Lock Actuator Replacement', serviceable: true, price: 150 },
  { fullname: 'Ignition Switch Replacement', serviceable: true, price: 120 },
  { fullname: 'Sunroof Motor Replacement', serviceable: false, price: 300 },
  { fullname: 'MAP Sensor Replacement', serviceable: true, price: 80 },
  {
    fullname: 'ABS Control Module Replacement',
    serviceable: false,
    price: 400,
  },
  {
    fullname: 'Cylinder Head Gasket Replacement',
    serviceable: true,
    price: 600,
  },
  { fullname: 'Radiator Fan Replacement', serviceable: true, price: 200 },
  { fullname: 'Windshield Replacement', serviceable: false, price: 250 },
  { fullname: 'Door Handle Replacement', serviceable: true, price: 100 },
  { fullname: 'Blower Motor Replacement', serviceable: true, price: 150 },
  { fullname: 'Heater Core Replacement', serviceable: false, price: 400 },
];

export const companies = [
  { fullname: 'Toyota' },
  { fullname: 'Ford' },
  { fullname: 'Honda' },
  { fullname: 'BMW' },
  { fullname: 'Mercedes-Benz' },
];
